select
    md5(concat_ws(
        '|',
        annee_financiere,
        cumul_periode::varchar,
        coalesce(rss_code, ''),
        coalesce(region, ''),
        coalesce(nom_etablissement, ''),
        coalesce(nom_installation, ''),
        coalesce(no_permis_installation, '')
    )) as emergency_cumulative_key,
    annee_financiere,
    cumul_periode,
    rss_code,
    region,
    nom_etablissement,
    nom_installation,
    no_permis_installation,
    niveau_agregation,
    nb_visites_total,
    nb_usagers_75ans_et_plus_total,
    nb_usagers_sante_mentale_total,
    dms_total_heures,
    nb_usagers_pec_total,
    delai_pec_total_heures,
    nb_visites_ambulatoire,
    nb_usagers_75ans_et_plus_ambulatoire,
    nb_usagers_sante_mentale_ambulatoire,
    dms_ambulatoire_heures,
    nb_usagers_pec_ambulatoire,
    delai_pec_ambulatoire_heures,
    nb_visites_sur_civiere,
    nb_usagers_sur_civiere_plus_24h,
    nb_usagers_sur_civiere_plus_48h,
    dms_sur_civiere_heures,
    nb_usagers_pec_sur_civiere,
    delai_pec_sur_civiere_heures,
    nb_usagers_75ans_et_plus_civiere,
    nb_usagers_sante_mentale_civiere,
    source_file,
    loaded_at
from {{ ref('stg_urgences_cumulatives') }}
