select
    md5(concat_ws('|', no_permis_installation, date_heure_mise_a_jour::varchar)) as emergency_snapshot_key,
    md5(no_permis_installation) as facility_key,
    md5(coalesce(rss_code, region)) as region_key,
    to_number(to_char(date_heure_mise_a_jour::date, 'YYYYMMDD')) as date_key,
    hour(date_heure_mise_a_jour) * 100 + minute(date_heure_mise_a_jour) as time_key,
    date_heure_mise_a_jour as snapshot_at,
    no_permis_installation as installation_id,
    nombre_civieres_fonctionnelles,
    nombre_civieres_occupees,
    nombre_patients_civiere_plus_24h,
    nombre_patients_civiere_plus_48h,
    nombre_patients_presents,
    nombre_patients_attente_pec,
    dms_civiere_heures,
    dms_ambulatoire_heures,
    taux_occupation_pct,
    niveau_occupation,
    source_file,
    loaded_at
from {{ ref('int_urgences_enrichies') }}
