USE ROLE ACCOUNTADMIN;

CREATE ROLE IF NOT EXISTS QUEBEC_HEALTH_INGESTION
    COMMENT = 'Chargement des sources dans RAW et journalisation des executions';

CREATE ROLE IF NOT EXISTS QUEBEC_HEALTH_TRANSFORM
    COMMENT = 'Transformations dbt dans STAGING, INTERMEDIATE et MARTS';

CREATE ROLE IF NOT EXISTS QUEBEC_HEALTH_ANALYST
    COMMENT = 'Consultation des modeles analytiques publies dans MARTS';

GRANT ROLE QUEBEC_HEALTH_INGESTION TO ROLE SYSADMIN;
GRANT ROLE QUEBEC_HEALTH_TRANSFORM TO ROLE SYSADMIN;
GRANT ROLE QUEBEC_HEALTH_ANALYST TO ROLE SYSADMIN;

GRANT USAGE ON WAREHOUSE HEALTH_ELT_WH TO ROLE QUEBEC_HEALTH_INGESTION;
GRANT USAGE ON WAREHOUSE HEALTH_ELT_WH TO ROLE QUEBEC_HEALTH_TRANSFORM;
GRANT USAGE ON WAREHOUSE HEALTH_ELT_WH TO ROLE QUEBEC_HEALTH_ANALYST;

GRANT USAGE ON DATABASE QUEBEC_HEALTH_DWH TO ROLE QUEBEC_HEALTH_INGESTION;
GRANT USAGE ON SCHEMA QUEBEC_HEALTH_DWH.RAW TO ROLE QUEBEC_HEALTH_INGESTION;
GRANT USAGE ON SCHEMA QUEBEC_HEALTH_DWH.AUDIT TO ROLE QUEBEC_HEALTH_INGESTION;
GRANT CREATE STAGE ON SCHEMA QUEBEC_HEALTH_DWH.RAW TO ROLE QUEBEC_HEALTH_INGESTION;
GRANT CREATE FILE FORMAT ON SCHEMA QUEBEC_HEALTH_DWH.RAW TO ROLE QUEBEC_HEALTH_INGESTION;
GRANT CREATE TABLE ON SCHEMA QUEBEC_HEALTH_DWH.RAW TO ROLE QUEBEC_HEALTH_INGESTION;
GRANT CREATE TABLE ON SCHEMA QUEBEC_HEALTH_DWH.AUDIT TO ROLE QUEBEC_HEALTH_INGESTION;
GRANT SELECT, INSERT, DELETE ON ALL TABLES IN SCHEMA QUEBEC_HEALTH_DWH.RAW
    TO ROLE QUEBEC_HEALTH_INGESTION;
GRANT SELECT, INSERT, DELETE ON FUTURE TABLES IN SCHEMA QUEBEC_HEALTH_DWH.RAW
    TO ROLE QUEBEC_HEALTH_INGESTION;
GRANT READ, WRITE ON STAGE QUEBEC_HEALTH_DWH.RAW.HEALTH_SOURCE_FILES
    TO ROLE QUEBEC_HEALTH_INGESTION;
GRANT USAGE ON FILE FORMAT QUEBEC_HEALTH_DWH.RAW.CSV_URGENCES_CP1252
    TO ROLE QUEBEC_HEALTH_INGESTION;
GRANT USAGE ON FILE FORMAT QUEBEC_HEALTH_DWH.RAW.CSV_URGENCES_CUMUL_UTF8
    TO ROLE QUEBEC_HEALTH_INGESTION;

GRANT USAGE ON DATABASE QUEBEC_HEALTH_DWH TO ROLE QUEBEC_HEALTH_TRANSFORM;
GRANT USAGE ON SCHEMA QUEBEC_HEALTH_DWH.RAW TO ROLE QUEBEC_HEALTH_TRANSFORM;
GRANT USAGE ON SCHEMA QUEBEC_HEALTH_DWH.STAGING TO ROLE QUEBEC_HEALTH_TRANSFORM;
GRANT USAGE ON SCHEMA QUEBEC_HEALTH_DWH.INTERMEDIATE TO ROLE QUEBEC_HEALTH_TRANSFORM;
GRANT USAGE ON SCHEMA QUEBEC_HEALTH_DWH.MARTS TO ROLE QUEBEC_HEALTH_TRANSFORM;
GRANT SELECT ON ALL TABLES IN SCHEMA QUEBEC_HEALTH_DWH.RAW TO ROLE QUEBEC_HEALTH_TRANSFORM;
GRANT SELECT ON FUTURE TABLES IN SCHEMA QUEBEC_HEALTH_DWH.RAW TO ROLE QUEBEC_HEALTH_TRANSFORM;
GRANT CREATE TABLE ON SCHEMA QUEBEC_HEALTH_DWH.STAGING TO ROLE QUEBEC_HEALTH_TRANSFORM;
GRANT CREATE VIEW ON SCHEMA QUEBEC_HEALTH_DWH.STAGING TO ROLE QUEBEC_HEALTH_TRANSFORM;
GRANT CREATE TABLE ON SCHEMA QUEBEC_HEALTH_DWH.INTERMEDIATE TO ROLE QUEBEC_HEALTH_TRANSFORM;
GRANT CREATE VIEW ON SCHEMA QUEBEC_HEALTH_DWH.INTERMEDIATE TO ROLE QUEBEC_HEALTH_TRANSFORM;
GRANT CREATE TABLE ON SCHEMA QUEBEC_HEALTH_DWH.MARTS TO ROLE QUEBEC_HEALTH_TRANSFORM;
GRANT CREATE VIEW ON SCHEMA QUEBEC_HEALTH_DWH.MARTS TO ROLE QUEBEC_HEALTH_TRANSFORM;

GRANT USAGE ON DATABASE QUEBEC_HEALTH_DWH TO ROLE QUEBEC_HEALTH_ANALYST;
GRANT USAGE ON SCHEMA QUEBEC_HEALTH_DWH.MARTS TO ROLE QUEBEC_HEALTH_ANALYST;
GRANT SELECT ON ALL TABLES IN SCHEMA QUEBEC_HEALTH_DWH.MARTS TO ROLE QUEBEC_HEALTH_ANALYST;
GRANT SELECT ON FUTURE TABLES IN SCHEMA QUEBEC_HEALTH_DWH.MARTS TO ROLE QUEBEC_HEALTH_ANALYST;
GRANT SELECT ON ALL VIEWS IN SCHEMA QUEBEC_HEALTH_DWH.MARTS TO ROLE QUEBEC_HEALTH_ANALYST;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA QUEBEC_HEALTH_DWH.MARTS TO ROLE QUEBEC_HEALTH_ANALYST;

SHOW ROLES LIKE 'QUEBEC_HEALTH_%';
