USE ROLE ACCOUNTADMIN;
USE WAREHOUSE HEALTH_ELT_WH;
USE DATABASE QUEBEC_HEALTH_DWH;
USE SCHEMA AUDIT;

CREATE TABLE IF NOT EXISTS INGESTION_RUN (
    RUN_ID VARCHAR NOT NULL,
    BATCH_ID VARCHAR NOT NULL,
    SOURCE_SYSTEM VARCHAR NOT NULL,
    SOURCE_DATASET VARCHAR NOT NULL,
    SOURCE_FILE VARCHAR NOT NULL,
    SOURCE_SHA256 VARCHAR NOT NULL,
    STARTED_AT TIMESTAMP_TZ NOT NULL,
    COMPLETED_AT TIMESTAMP_TZ,
    ROWS_RECEIVED NUMBER,
    ROWS_LOADED NUMBER,
    ROWS_REJECTED NUMBER,
    STATUS VARCHAR NOT NULL,
    ERROR_MESSAGE VARCHAR,
    CONSTRAINT PK_INGESTION_RUN PRIMARY KEY (RUN_ID)
)
COMMENT = 'Journal technique des exécutions des pipelines d ingestion';

ALTER TABLE QUEBEC_HEALTH_DWH.RAW.URGENCES_HORAIRES_RAW
    ADD COLUMN IF NOT EXISTS BATCH_ID VARCHAR;

ALTER TABLE QUEBEC_HEALTH_DWH.RAW.URGENCES_HORAIRES_RAW
    ADD COLUMN IF NOT EXISTS FILE_MODIFIED_AT TIMESTAMP_TZ;

GRANT USAGE ON SCHEMA QUEBEC_HEALTH_DWH.AUDIT TO ROLE QUEBEC_HEALTH_INGESTION;
GRANT SELECT, INSERT, UPDATE ON TABLE QUEBEC_HEALTH_DWH.AUDIT.INGESTION_RUN
    TO ROLE QUEBEC_HEALTH_INGESTION;
