USE ROLE QUEBEC_HEALTH_ANALYST;
USE WAREHOUSE HEALTH_ELT_WH;
USE DATABASE QUEBEC_HEALTH_DWH;
USE SCHEMA MARTS;

-- Vue d'ensemble du plus récent instantané disponible.
SELECT
    MAX(SNAPSHOT_AT) AS SNAPSHOT_AT,
    COUNT(DISTINCT RSS_CODE) AS NOMBRE_REGIONS,
    SUM(NOMBRE_INSTALLATIONS) AS NOMBRE_INSTALLATIONS,
    SUM(NOMBRE_CIVIERES_FONCTIONNELLES) AS CIVIERES_FONCTIONNELLES,
    SUM(NOMBRE_CIVIERES_OCCUPEES) AS CIVIERES_OCCUPEES,
    ROUND(
        100.0 * SUM(NOMBRE_CIVIERES_OCCUPEES)
        / NULLIF(SUM(NOMBRE_CIVIERES_FONCTIONNELLES), 0),
        2
    ) AS TAUX_OCCUPATION_GLOBAL_PCT,
    SUM(INSTALLATIONS_EN_SURCAPACITE) AS INSTALLATIONS_EN_SURCAPACITE,
    SUM(NOMBRE_PATIENTS_CIVIERE_PLUS_24H) AS PATIENTS_PLUS_24H,
    SUM(NOMBRE_PATIENTS_CIVIERE_PLUS_48H) AS PATIENTS_PLUS_48H
FROM MART_URGENCES_REGIONALES
WHERE SNAPSHOT_AT = (
    SELECT MAX(SNAPSHOT_AT)
    FROM MART_URGENCES_REGIONALES
);

-- Classement régional selon le taux d'occupation des civières.
SELECT
    SNAPSHOT_AT,
    RSS_CODE,
    REGION,
    NOMBRE_INSTALLATIONS,
    INSTALLATIONS_EN_SURCAPACITE,
    TAUX_OCCUPATION_PCT,
    NOMBRE_PATIENTS_CIVIERE_PLUS_24H,
    NOMBRE_PATIENTS_CIVIERE_PLUS_48H,
    DMS_CIVIERE_MOYENNE_HEURES
FROM MART_URGENCES_REGIONALES
QUALIFY SNAPSHOT_AT = MAX(SNAPSHOT_AT) OVER ()
ORDER BY TAUX_OCCUPATION_PCT DESC NULLS LAST;

-- Installations qui demandent une attention prioritaire.
SELECT
    faits.SNAPSHOT_AT,
    dimension.REGION,
    dimension.NOM_INSTALLATION,
    faits.NOMBRE_CIVIERES_FONCTIONNELLES,
    faits.NOMBRE_CIVIERES_OCCUPEES,
    faits.TAUX_OCCUPATION_PCT,
    faits.NOMBRE_PATIENTS_CIVIERE_PLUS_24H,
    faits.NOMBRE_PATIENTS_CIVIERE_PLUS_48H,
    faits.DMS_CIVIERE_HEURES,
    faits.NIVEAU_OCCUPATION
FROM FCT_URGENCES_HORAIRES AS faits
INNER JOIN DIM_INSTALLATIONS_URGENCE AS dimension
    ON faits.INSTALLATION_ID = dimension.INSTALLATION_ID
QUALIFY faits.SNAPSHOT_AT = MAX(faits.SNAPSHOT_AT) OVER ()
ORDER BY
    faits.TAUX_OCCUPATION_PCT DESC NULLS LAST,
    faits.NOMBRE_PATIENTS_CIVIERE_PLUS_24H DESC;
