USE ROLE QUEBEC_HEALTH_TRANSFORM;
USE WAREHOUSE HEALTH_ELT_WH;
USE DATABASE QUEBEC_HEALTH_DWH;
USE SCHEMA INTERMEDIATE;

CREATE OR REPLACE VIEW INT_URGENCES_ENRICHIES AS
WITH urgences AS (
    SELECT
        *,
        ROUND(
            100.0 * NOMBRE_CIVIERES_OCCUPEES
            / NULLIF(NOMBRE_CIVIERES_FONCTIONNELLES, 0),
            2
        ) AS TAUX_OCCUPATION_PCT
    FROM QUEBEC_HEALTH_DWH.STAGING.STG_URGENCES_HORAIRES
    WHERE NIVEAU_AGREGATION = 'INSTALLATION'
)

SELECT
    urgence.DATE_HEURE_MISE_A_JOUR,
    urgence.HEURE_EXTRACTION,
    urgence.RSS_CODE,
    urgence.REGION,
    urgence.NO_PERMIS_INSTALLATION,
    urgence.NOM_INSTALLATION,
    urgence.NOM_ETABLISSEMENT,
    installation.ETABLISSEMENT_CODE,
    installation.MUNICIPALITE_CODE,
    installation.MUNICIPALITE_NOM,
    installation.RLS_CODE,
    installation.RLS_NOM,
    installation.RUIS_CODE,
    installation.RUIS_NOM,
    installation.LONGITUDE,
    installation.LATITUDE,
    urgence.NOMBRE_CIVIERES_FONCTIONNELLES,
    urgence.NOMBRE_CIVIERES_OCCUPEES,
    urgence.NOMBRE_PATIENTS_CIVIERE_PLUS_24H,
    urgence.NOMBRE_PATIENTS_CIVIERE_PLUS_48H,
    urgence.NOMBRE_PATIENTS_PRESENTS,
    urgence.NOMBRE_PATIENTS_ATTENTE_PEC,
    urgence.DMS_CIVIERE_HEURES,
    urgence.DMS_AMBULATOIRE_HEURES,
    urgence.TAUX_OCCUPATION_PCT,
    CASE
        WHEN urgence.TAUX_OCCUPATION_PCT IS NULL THEN 'NON_CALCULABLE'
        WHEN urgence.TAUX_OCCUPATION_PCT > 100 THEN 'SURCAPACITE'
        WHEN urgence.TAUX_OCCUPATION_PCT >= 90 THEN 'ELEVE'
        ELSE 'NORMAL'
    END AS NIVEAU_OCCUPATION,
    urgence.SOURCE_FILE,
    urgence.LOADED_AT
FROM urgences AS urgence
LEFT JOIN QUEBEC_HEALTH_DWH.STAGING.STG_INSTALLATIONS AS installation
    ON urgence.NO_PERMIS_INSTALLATION = installation.INSTALLATION_CODE;

SELECT
    COUNT(*) AS NOMBRE_URGENCES,
    COUNT(DISTINCT NO_PERMIS_INSTALLATION) AS INSTALLATIONS_DISTINCTES,
    COUNT_IF(ETABLISSEMENT_CODE IS NULL) AS INSTALLATIONS_NON_ASSOCIEES,
    COUNT_IF(TAUX_OCCUPATION_PCT IS NULL) AS TAUX_NON_CALCULABLES,
    COUNT_IF(TAUX_OCCUPATION_PCT > 100) AS TAUX_SUPERIEURS_A_100
FROM INT_URGENCES_ENRICHIES;

SELECT
    NIVEAU_OCCUPATION,
    COUNT(*) AS NOMBRE_URGENCES
FROM INT_URGENCES_ENRICHIES
GROUP BY NIVEAU_OCCUPATION
ORDER BY NIVEAU_OCCUPATION;
