USE ROLE QUEBEC_HEALTH_TRANSFORM;
USE WAREHOUSE HEALTH_ELT_WH;
USE DATABASE QUEBEC_HEALTH_DWH;
USE SCHEMA MARTS;

CREATE OR REPLACE VIEW DIM_INSTALLATIONS_URGENCE AS
SELECT DISTINCT
    NO_PERMIS_INSTALLATION AS INSTALLATION_ID,
    NOM_INSTALLATION,
    NOM_ETABLISSEMENT,
    ETABLISSEMENT_CODE,
    RSS_CODE,
    REGION,
    MUNICIPALITE_CODE,
    MUNICIPALITE_NOM,
    RLS_CODE,
    RLS_NOM,
    RUIS_CODE,
    RUIS_NOM,
    LONGITUDE,
    LATITUDE
FROM QUEBEC_HEALTH_DWH.INTERMEDIATE.INT_URGENCES_ENRICHIES;

CREATE OR REPLACE VIEW FCT_URGENCES_HORAIRES AS
SELECT
    DATE_HEURE_MISE_A_JOUR AS SNAPSHOT_AT,
    NO_PERMIS_INSTALLATION AS INSTALLATION_ID,
    NOMBRE_CIVIERES_FONCTIONNELLES,
    NOMBRE_CIVIERES_OCCUPEES,
    NOMBRE_PATIENTS_CIVIERE_PLUS_24H,
    NOMBRE_PATIENTS_CIVIERE_PLUS_48H,
    NOMBRE_PATIENTS_PRESENTS,
    NOMBRE_PATIENTS_ATTENTE_PEC,
    DMS_CIVIERE_HEURES,
    DMS_AMBULATOIRE_HEURES,
    TAUX_OCCUPATION_PCT,
    NIVEAU_OCCUPATION,
    SOURCE_FILE,
    LOADED_AT
FROM QUEBEC_HEALTH_DWH.INTERMEDIATE.INT_URGENCES_ENRICHIES;

CREATE OR REPLACE VIEW MART_URGENCES_REGIONALES AS
SELECT
    urgence.DATE_HEURE_MISE_A_JOUR AS SNAPSHOT_AT,
    urgence.RSS_CODE,
    urgence.REGION,
    COUNT(*) AS NOMBRE_INSTALLATIONS,
    COUNT_IF(urgence.TAUX_OCCUPATION_PCT IS NOT NULL) AS INSTALLATIONS_AVEC_CAPACITE,
    COUNT_IF(urgence.TAUX_OCCUPATION_PCT > 100) AS INSTALLATIONS_EN_SURCAPACITE,
    SUM(urgence.NOMBRE_CIVIERES_FONCTIONNELLES) AS NOMBRE_CIVIERES_FONCTIONNELLES,
    SUM(urgence.NOMBRE_CIVIERES_OCCUPEES) AS NOMBRE_CIVIERES_OCCUPEES,
    SUM(urgence.NOMBRE_PATIENTS_CIVIERE_PLUS_24H) AS NOMBRE_PATIENTS_CIVIERE_PLUS_24H,
    SUM(urgence.NOMBRE_PATIENTS_CIVIERE_PLUS_48H) AS NOMBRE_PATIENTS_CIVIERE_PLUS_48H,
    SUM(urgence.NOMBRE_PATIENTS_PRESENTS) AS NOMBRE_PATIENTS_PRESENTS,
    SUM(urgence.NOMBRE_PATIENTS_ATTENTE_PEC) AS NOMBRE_PATIENTS_ATTENTE_PEC,
    ROUND(
        100.0 * SUM(urgence.NOMBRE_CIVIERES_OCCUPEES)
        / NULLIF(SUM(urgence.NOMBRE_CIVIERES_FONCTIONNELLES), 0),
        2
    ) AS TAUX_OCCUPATION_PCT,
    ROUND(AVG(urgence.DMS_CIVIERE_HEURES), 2) AS DMS_CIVIERE_MOYENNE_HEURES,
    ROUND(AVG(urgence.DMS_AMBULATOIRE_HEURES), 2) AS DMS_AMBULATOIRE_MOYENNE_HEURES
FROM QUEBEC_HEALTH_DWH.INTERMEDIATE.INT_URGENCES_ENRICHIES AS urgence
GROUP BY
    urgence.DATE_HEURE_MISE_A_JOUR,
    urgence.RSS_CODE,
    urgence.REGION;

SELECT
    (SELECT COUNT(*) FROM DIM_INSTALLATIONS_URGENCE) AS DIMENSION_ROWS,
    (SELECT COUNT(*) FROM FCT_URGENCES_HORAIRES) AS FACT_ROWS,
    (SELECT COUNT(*) FROM MART_URGENCES_REGIONALES) AS REGIONAL_ROWS,
    (SELECT COUNT(*) FROM FCT_URGENCES_HORAIRES)
        - (SELECT COUNT(DISTINCT INSTALLATION_ID) FROM FCT_URGENCES_HORAIRES)
        AS DUPLICATE_INSTALLATION_SNAPSHOTS;
