USE ROLE ACCOUNTADMIN;
USE WAREHOUSE HEALTH_ELT_WH;
USE DATABASE QUEBEC_HEALTH_DWH;
USE SCHEMA RAW;

CREATE FILE FORMAT IF NOT EXISTS CSV_URGENCES_CP1252
    TYPE = CSV
    FIELD_DELIMITER = ','
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    ENCODING = 'WINDOWS1252'
    TRIM_SPACE = TRUE
    EMPTY_FIELD_AS_NULL = TRUE
    NULL_IF = ('', 'NULL');

CREATE FILE FORMAT IF NOT EXISTS CSV_INSTALLATIONS_UTF8
    TYPE = CSV
    FIELD_DELIMITER = ','
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    ENCODING = 'UTF8'
    TRIM_SPACE = TRUE
    EMPTY_FIELD_AS_NULL = TRUE
    NULL_IF = ('', 'NULL');

CREATE FILE FORMAT IF NOT EXISTS CSV_URGENCES_CUMUL_UTF8
    TYPE = CSV
    FIELD_DELIMITER = ','
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    ENCODING = 'UTF8'
    TRIM_SPACE = TRUE
    EMPTY_FIELD_AS_NULL = TRUE
    NULL_IF = ('', 'NULL');

CREATE STAGE IF NOT EXISTS HEALTH_SOURCE_FILES
    DIRECTORY = (ENABLE = TRUE)
    COMMENT = 'Zone interne des fichiers sources publics du MSSS';

CREATE TABLE IF NOT EXISTS URGENCES_HORAIRES_RAW (
    RSS VARCHAR,
    REGION VARCHAR,
    NOM_ETABLISSEMENT VARCHAR,
    NOM_INSTALLATION VARCHAR,
    NO_PERMIS_INSTALLATION VARCHAR,
    NOMBRE_DE_CIVIERES_FONCTIONNELLES VARCHAR,
    NOMBRE_DE_CIVIERES_OCCUPEES VARCHAR,
    NOMBRE_DE_PATIENTS_SUR_CIVIERE_PLUS_DE_24_HEURES VARCHAR,
    NOMBRE_DE_PATIENTS_SUR_CIVIERE_PLUS_DE_48_HEURES VARCHAR,
    NOMBRE_TOTAL_DE_PATIENTS_PRESENTS_A_LURGENCE VARCHAR,
    NOMBRE_TOTAL_DE_PATIENTS_EN_ATTENTE_DE_PEC VARCHAR,
    DMS_SUR_CIVIERE VARCHAR,
    DMS_AMBULATOIRE VARCHAR,
    DMS_SUR_CIVIERE_HORAIRE VARCHAR,
    DMS_AMBULATOIRE_HORAIRE VARCHAR,
    HEURE_EXTRACTION_IMAGE VARCHAR,
    MISE_A_JOUR VARCHAR,
    SOURCE_FILE VARCHAR,
    LOADED_AT TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP()
)
COMMENT = 'Copie brute des releves horaires des urgences';

CREATE TABLE IF NOT EXISTS INSTALLATIONS_RAW (
    INSTAL_COD VARCHAR,
    INSTAL_NOM VARCHAR,
    INSTAL_N_1 VARCHAR,
    ETAB_CODE VARCHAR,
    ETAB_NOM VARCHAR,
    ETAB_NOM_A VARCHAR,
    RSS_CODE VARCHAR,
    RSS_NOM VARCHAR,
    ADRESSE VARCHAR,
    CASE_POST VARCHAR,
    CODE_POSTA VARCHAR,
    MUN_CODE VARCHAR,
    MUN_NOM VARCHAR,
    CLSC_CODE VARCHAR,
    CLSC_NOM VARCHAR,
    MRC_CODE VARCHAR,
    MRC_NOM VARCHAR,
    RLS_CODE VARCHAR,
    RLS_NOM VARCHAR,
    RUIS_CODE VARCHAR,
    RUIS_NOM VARCHAR,
    STATUT_COD VARCHAR,
    MD_CONS_CO VARCHAR,
    MD_FINAN_C VARCHAR,
    DESIGN_MIN VARCHAR,
    INSTANCE VARCHAR,
    DATE_INCOR VARCHAR,
    DATE_OUVER VARCHAR,
    LONGITUDE VARCHAR,
    LATITUDE VARCHAR,
    CHPSY VARCHAR,
    CHSGS VARCHAR,
    CHSLD VARCHAR,
    CLSC VARCHAR,
    CPEJ VARCHAR,
    CRDITED VARCHAR,
    CRDPA VARCHAR,
    CRDPM VARCHAR,
    CRDPV VARCHAR,
    CRDPL VARCHAR,
    CRJDA VARCHAR,
    CRMDA VARCHAR,
    CRD VARCHAR,
    DATE_MAJ VARCHAR,
    SOURCE_FILE VARCHAR,
    LOADED_AT TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP()
)
COMMENT = 'Copie brute du referentiel des installations de sante';

CREATE TABLE IF NOT EXISTS URGENCES_CUMULATIVES_RAW (
    ANNEE VARCHAR,
    CUMUL_PERIODE VARCHAR,
    RSS VARCHAR,
    REGION VARCHAR,
    NOM_ETABLISSEMENT VARCHAR,
    NOM_INSTALLATION VARCHAR,
    NO_PERMIS_INSTALLATION VARCHAR,
    NB_VISITES_TOTAL VARCHAR,
    NB_USAGERS_75ANS_ET_PLUS_TOTAL VARCHAR,
    NB_USAGERS_SANTE_MENTALE_TOTAL VARCHAR,
    DMS_TOTAL VARCHAR,
    NB_USAGERS_PEC_TOTAL VARCHAR,
    DELAI_PEC_TOTAL VARCHAR,
    NB_VISITES_AMBULATOIRE VARCHAR,
    NB_USAGERS_75ANS_ET_PLUS_AMB VARCHAR,
    NB_USAGERS_SANTE_MENTALE_AMB VARCHAR,
    DMS_AMBULATOIRE VARCHAR,
    NB_USAGERS_PEC_AMBULATOIRE VARCHAR,
    DELAI_PEC_AMBULATOIRE VARCHAR,
    NB_VISITES_SUR_CIVIERE VARCHAR,
    NB_USAGERS_SUR_CIVIERE_PLUS_24H VARCHAR,
    NB_USAGERS_SUR_CIVIERE_PLUS_48H VARCHAR,
    DMS_SUR_CIVIERE VARCHAR,
    NB_USAGERS_PEC_SUR_CIVIERE VARCHAR,
    DELAI_PEC_SUR_CIVIERE VARCHAR,
    NB_USAGERS_75ANS_ET_PLUS_CIV VARCHAR,
    NB_USAGERS_SANTE_MENTALE_CIV VARCHAR,
    SOURCE_FILE VARCHAR,
    BATCH_ID VARCHAR,
    FILE_MODIFIED_AT TIMESTAMP_TZ,
    LOADED_AT TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP()
)
COMMENT = 'Copie brute des indicateurs cumulatifs des urgences';

SHOW TABLES IN SCHEMA QUEBEC_HEALTH_DWH.RAW;
