USE ROLE QUEBEC_HEALTH_TRANSFORM;
USE WAREHOUSE HEALTH_ELT_WH;
USE DATABASE QUEBEC_HEALTH_DWH;
USE SCHEMA STAGING;

CREATE OR REPLACE VIEW STG_URGENCES_HORAIRES AS
SELECT
    NULLIF(TRIM(RSS), '') AS RSS_CODE,
    NULLIF(TRIM(REGION), '') AS REGION,
    NULLIF(TRIM(NOM_ETABLISSEMENT), '') AS NOM_ETABLISSEMENT,
    NULLIF(TRIM(NOM_INSTALLATION), '') AS NOM_INSTALLATION,
    NULLIF(TRIM(NO_PERMIS_INSTALLATION), '') AS NO_PERMIS_INSTALLATION,
    TRY_TO_NUMBER(NULLIF(TRIM(NOMBRE_DE_CIVIERES_FONCTIONNELLES), ''))
        AS NOMBRE_CIVIERES_FONCTIONNELLES,
    TRY_TO_NUMBER(NULLIF(TRIM(NOMBRE_DE_CIVIERES_OCCUPEES), ''))
        AS NOMBRE_CIVIERES_OCCUPEES,
    TRY_TO_NUMBER(NULLIF(TRIM(NOMBRE_DE_PATIENTS_SUR_CIVIERE_PLUS_DE_24_HEURES), ''))
        AS NOMBRE_PATIENTS_CIVIERE_PLUS_24H,
    TRY_TO_NUMBER(NULLIF(TRIM(NOMBRE_DE_PATIENTS_SUR_CIVIERE_PLUS_DE_48_HEURES), ''))
        AS NOMBRE_PATIENTS_CIVIERE_PLUS_48H,
    TRY_TO_NUMBER(NULLIF(TRIM(NOMBRE_TOTAL_DE_PATIENTS_PRESENTS_A_LURGENCE), ''))
        AS NOMBRE_PATIENTS_PRESENTS,
    TRY_TO_NUMBER(NULLIF(TRIM(NOMBRE_TOTAL_DE_PATIENTS_EN_ATTENTE_DE_PEC), ''))
        AS NOMBRE_PATIENTS_ATTENTE_PEC,
    TRY_TO_DECIMAL(NULLIF(TRIM(DMS_SUR_CIVIERE), ''), 18, 6) AS DMS_CIVIERE_HEURES,
    TRY_TO_DECIMAL(NULLIF(TRIM(DMS_AMBULATOIRE), ''), 18, 6) AS DMS_AMBULATOIRE_HEURES,
    TRY_TO_TIME(NULLIF(TRIM(DMS_SUR_CIVIERE_HORAIRE), '')) AS DMS_CIVIERE_AFFICHAGE,
    TRY_TO_TIME(NULLIF(TRIM(DMS_AMBULATOIRE_HORAIRE), '')) AS DMS_AMBULATOIRE_AFFICHAGE,
    TRY_TO_TIME(NULLIF(TRIM(HEURE_EXTRACTION_IMAGE), '')) AS HEURE_EXTRACTION,
    TRY_TO_TIMESTAMP_NTZ(NULLIF(TRIM(MISE_A_JOUR), '')) AS DATE_HEURE_MISE_A_JOUR,
    CASE
        WHEN UPPER(TRIM(NOM_INSTALLATION)) IN ('ENSEMBLE DU QUÉBEC', 'TOTAL PROVINCIAL')
            THEN 'PROVINCIAL'
        WHEN UPPER(TRIM(NOM_INSTALLATION)) = 'TOTAL RÉGIONAL' THEN 'REGIONAL'
        ELSE 'INSTALLATION'
    END AS NIVEAU_AGREGATION,
    SOURCE_FILE,
    LOADED_AT
FROM QUEBEC_HEALTH_DWH.RAW.URGENCES_HORAIRES_RAW;

CREATE OR REPLACE VIEW STG_INSTALLATIONS AS
SELECT
    NULLIF(TRIM(INSTAL_COD), '') AS INSTALLATION_CODE,
    NULLIF(TRIM(INSTAL_NOM), '') AS INSTALLATION_NOM,
    NULLIF(TRIM(INSTAL_N_1), '') AS INSTALLATION_NOM_COURT,
    NULLIF(TRIM(ETAB_CODE), '') AS ETABLISSEMENT_CODE,
    NULLIF(TRIM(ETAB_NOM), '') AS ETABLISSEMENT_NOM,
    NULLIF(TRIM(ETAB_NOM_A), '') AS ETABLISSEMENT_NOM_COURT,
    NULLIF(TRIM(RSS_CODE), '') AS RSS_CODE,
    NULLIF(TRIM(RSS_NOM), '') AS RSS_NOM,
    NULLIF(TRIM(ADRESSE), '') AS ADRESSE,
    NULLIF(TRIM(CASE_POST), '') AS CASE_POSTALE,
    NULLIF(TRIM(CODE_POSTA), '') AS CODE_POSTAL,
    NULLIF(TRIM(MUN_CODE), '') AS MUNICIPALITE_CODE,
    NULLIF(TRIM(MUN_NOM), '') AS MUNICIPALITE_NOM,
    NULLIF(TRIM(CLSC_CODE), '') AS CLSC_CODE,
    NULLIF(TRIM(CLSC_NOM), '') AS CLSC_NOM,
    NULLIF(TRIM(MRC_CODE), '') AS MRC_CODE,
    NULLIF(TRIM(MRC_NOM), '') AS MRC_NOM,
    NULLIF(TRIM(RLS_CODE), '') AS RLS_CODE,
    NULLIF(TRIM(RLS_NOM), '') AS RLS_NOM,
    NULLIF(TRIM(RUIS_CODE), '') AS RUIS_CODE,
    NULLIF(TRIM(RUIS_NOM), '') AS RUIS_NOM,
    NULLIF(TRIM(STATUT_COD), '') AS STATUT_CODE,
    NULLIF(TRIM(MD_CONS_CO), '') AS MODE_CONSTITUTION_CODE,
    NULLIF(TRIM(MD_FINAN_C), '') AS MODE_FINANCEMENT_CODE,
    NULLIF(TRIM(DESIGN_MIN), '') AS DESIGNATION_MINISTERIELLE,
    NULLIF(TRIM(INSTANCE), '') AS INSTANCE,
    TRY_TO_DATE(NULLIF(TRIM(DATE_INCOR), '')) AS DATE_INCORPORATION,
    TRY_TO_DATE(NULLIF(TRIM(DATE_OUVER), '')) AS DATE_OUVERTURE,
    TRY_TO_DECIMAL(NULLIF(TRIM(LONGITUDE), ''), 12, 8) AS LONGITUDE,
    TRY_TO_DECIMAL(NULLIF(TRIM(LATITUDE), ''), 12, 8) AS LATITUDE,
    IFF(UPPER(TRIM(CHPSY)) = 'OUI', TRUE, FALSE) AS EST_CH_PSYCHIATRIQUE,
    IFF(UPPER(TRIM(CHSGS)) = 'OUI', TRUE, FALSE) AS EST_CH_GENERAL_SPECIALISE,
    IFF(UPPER(TRIM(CHSLD)) = 'OUI', TRUE, FALSE) AS EST_CHSLD,
    IFF(UPPER(TRIM(CLSC)) = 'OUI', TRUE, FALSE) AS EST_CLSC,
    IFF(UPPER(TRIM(CPEJ)) = 'OUI', TRUE, FALSE) AS EST_CPEJ,
    IFF(UPPER(TRIM(CRDITED)) = 'OUI', TRUE, FALSE) AS EST_CRDITED,
    IFF(UPPER(TRIM(CRDPA)) = 'OUI', TRUE, FALSE) AS EST_CRDPA,
    IFF(UPPER(TRIM(CRDPM)) = 'OUI', TRUE, FALSE) AS EST_CRDPM,
    IFF(UPPER(TRIM(CRDPV)) = 'OUI', TRUE, FALSE) AS EST_CRDPV,
    IFF(UPPER(TRIM(CRDPL)) = 'OUI', TRUE, FALSE) AS EST_CRDPL,
    IFF(UPPER(TRIM(CRJDA)) = 'OUI', TRUE, FALSE) AS EST_CRJDA,
    IFF(UPPER(TRIM(CRMDA)) = 'OUI', TRUE, FALSE) AS EST_CRMDA,
    IFF(UPPER(TRIM(CRD)) = 'OUI', TRUE, FALSE) AS EST_CRD,
    TRY_TO_DATE(NULLIF(TRIM(DATE_MAJ), '')) AS DATE_MISE_A_JOUR,
    SOURCE_FILE,
    LOADED_AT
FROM QUEBEC_HEALTH_DWH.RAW.INSTALLATIONS_RAW;

SELECT
    NIVEAU_AGREGATION,
    COUNT(*) AS ROW_COUNT
FROM STG_URGENCES_HORAIRES
GROUP BY NIVEAU_AGREGATION
ORDER BY NIVEAU_AGREGATION;

SELECT
    COUNT(*) AS ROW_COUNT,
    COUNT(DISTINCT INSTALLATION_CODE) AS DISTINCT_INSTALLATION_COUNT,
    COUNT_IF(INSTALLATION_CODE IS NULL) AS MISSING_INSTALLATION_CODE,
    COUNT_IF(LONGITUDE IS NULL OR LATITUDE IS NULL) AS MISSING_COORDINATES
FROM STG_INSTALLATIONS;
