USE ROLE ACCOUNTADMIN;
USE WAREHOUSE HEALTH_ELT_WH;

UPDATE QUEBEC_HEALTH_DWH.RAW.URGENCES_HORAIRES_RAW
SET
    SOURCE_FILE = 'urgences_horaires.csv',
    LOADED_AT = CURRENT_TIMESTAMP()
WHERE SOURCE_FILE IS NULL OR LOADED_AT IS NULL;

UPDATE QUEBEC_HEALTH_DWH.RAW.INSTALLATIONS_RAW
SET
    SOURCE_FILE = 'installations.csv',
    LOADED_AT = CURRENT_TIMESTAMP()
WHERE SOURCE_FILE IS NULL OR LOADED_AT IS NULL;

SELECT
    'URGENCES_HORAIRES_RAW' AS TABLE_NAME,
    COUNT(*) AS ROW_COUNT,
    COUNT_IF(
        CONTAINS(NOM_ETABLISSEMENT, '�')
        OR CONTAINS(NOM_INSTALLATION, '�')
    ) AS ENCODING_ERRORS,
    COUNT_IF(SOURCE_FILE IS NULL) AS MISSING_SOURCE_FILE,
    COUNT_IF(LOADED_AT IS NULL) AS MISSING_LOADED_AT
FROM QUEBEC_HEALTH_DWH.RAW.URGENCES_HORAIRES_RAW

UNION ALL

SELECT
    'INSTALLATIONS_RAW',
    COUNT(*),
    COUNT_IF(
        CONTAINS(INSTAL_NOM, '�')
        OR CONTAINS(ETAB_NOM, '�')
    ),
    COUNT_IF(SOURCE_FILE IS NULL),
    COUNT_IF(LOADED_AT IS NULL)
FROM QUEBEC_HEALTH_DWH.RAW.INSTALLATIONS_RAW

ORDER BY TABLE_NAME;
