name: quebec_health
version: 1.0.0
config-version: 2

profile: quebec_health

model-paths: ["models"]
clean-targets: ["target", "dbt_packages"]

models:
  quebec_health:
    staging:
      +schema: staging
      +materialized: view
    intermediate:
      +schema: intermediate
      +materialized: view
    marts:
      +schema: marts
      +materialized: view
    monitoring:
      +schema: marts
      +materialized: view
